version: "3.9"

services:
  dev_backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    container_name: dev_backend
    restart: unless-stopped
    env_file:
      - ../env/dev-cloud.env
    ports:
      - "8002:8000"
    volumes:
      - ../../runtime-reports:/opt/greenbrain-platform/runtime-reports
      - ../../releases:/opt/greenbrain-platform/releases:ro

  dev_frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    container_name: dev_frontend
    restart: unless-stopped
    environment:
      BACKEND_HOST: dev_backend:8000
    ports:
      - "8090:80"
    depends_on:
      - dev_backend
