server {
    listen 80;
    listen [::]:80;
    server_name greenbrain.it;

    return 301 https://www.greenbrain.it$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name app.greenbrain.it;

    return 301 https://www.greenbrain.it$request_uri;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name www.greenbrain.it;

    root /opt/greenbrain-platform/apps/frontend/dist;
    index index.html;

    location /api/v1/auth/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/cloud-sync/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name dev.greenbrain.it;

    root /opt/greenbrain-platform/apps/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8002;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name cliente1.greenbrain.it;

    root /opt/greenbrain-platform/apps/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}



server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.greenbrain.it;

    ssl_certificate /etc/letsencrypt/live/greenbrain.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/greenbrain.it/privkey.pem;

    root /opt/greenbrain-platform/apps/frontend/dist;
    index index.html;

    location /api/v1/auth/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/cloud-sync/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri /index.html;
    }
}
