from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Tuple
import secrets
import shutil
import tarfile
import tempfile


from app.repositories.customer_delivery_repository import (
    get_customer_by_id,
    get_delivery_row,
    mark_bundle_sent,
)
from app.repositories.customer_portal_repository import update_customer_last_download

RELEASES_ROOT = Path("/opt/greenbrain-platform/releases/customer-local")


def _version_key(version_name: str) -> Tuple[int, ...]:
    parts = []
    for chunk in version_name.split("."):
        try:
            parts.append(int(chunk))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def _find_latest_release_bundle() -> Path | None:
    if not RELEASES_ROOT.exists() or not RELEASES_ROOT.is_dir():
        return None

    candidates: list[tuple[Tuple[int, ...], Path]] = []

    for entry in RELEASES_ROOT.iterdir():
        if not entry.is_dir():
            continue

        version = entry.name.strip()
        bundle = entry / f"customer-local-{version}.tar.gz"
        if bundle.exists() and bundle.is_file():
            candidates.append((_version_key(version), bundle))

    if not candidates:
        return None

    candidates.sort(key=lambda item: item[0], reverse=True)
    return candidates[0][1]




def _extract_release_version_from_bundle_path(bundle_path: Path) -> str | None:
    name = bundle_path.name.strip()
    prefix = "customer-local-"
    suffix = ".tar.gz"
    if name.startswith(prefix) and name.endswith(suffix):
        return name[len(prefix):-len(suffix)] or None
    parent = bundle_path.parent.name.strip()
    if parent:
        return parent.replace("greenbrain-customer-local-", "") or None
    return None


def get_latest_available_release_version() -> str | None:
    bundle = _find_latest_release_bundle()
    if not bundle:
        return None
    return _extract_release_version_from_bundle_path(bundle)



def _safe_env_value(value: Any) -> str:
    return str(value or "").replace("\n", " ").replace("\r", " ").strip()


def _render_customer_env(base_env: str, customer_profile: Dict[str, Any], temp_password: str) -> str:
    tenant_code = _safe_env_value(customer_profile.get("tenant_code"))
    email = _safe_env_value(customer_profile.get("portal_user_email") or customer_profile.get("contact_email"))
    full_name = _safe_env_value(customer_profile.get("company_name") or customer_profile.get("contact_name") or email)
    home_host = f"{tenant_code}.greenbrain.it" if tenant_code else "CHANGE_ME.greenbrain.it"

    overrides = {
        "LOCAL_CUSTOMER_EMAIL": email,
        "LOCAL_CUSTOMER_FULL_NAME": full_name,
        "LOCAL_CUSTOMER_TEMP_PASSWORD": temp_password,
        "LOCAL_CUSTOMER_TENANT_CODE": tenant_code,
        "LOCAL_CUSTOMER_HOME_HOST": home_host,
        "LOCAL_CUSTOMER_HOME_PATH": "/dashboard",
    }

    lines = []
    seen = set()
    for line in base_env.splitlines():
        key = line.split("=", 1)[0].strip() if "=" in line and not line.strip().startswith("#") else None
        if key in overrides:
            lines.append(f"{key}={overrides[key]}")
            seen.add(key)
        else:
            lines.append(line)

    lines.append("")
    lines.append("# Runtime customer local user provisioning - generated by GreenBrain cloud")
    for key, value in overrides.items():
        if key not in seen:
            lines.append(f"{key}={value}")

    return "\n".join(lines).rstrip() + "\n"


def _build_personalized_bundle(source_bundle: Path, customer_profile: Dict[str, Any]) -> Path:
    customer_id = _safe_env_value(customer_profile.get("customer_id"))
    tenant_code = _safe_env_value(customer_profile.get("tenant_code"))
    if not customer_id or not tenant_code:
        raise RuntimeError("customer_profile_missing_customer_id_or_tenant_code")

    version = _extract_release_version_from_bundle_path(source_bundle) or "unknown"
    out_dir = Path("/tmp/greenbrain-customer-bundles")
    out_dir.mkdir(parents=True, exist_ok=True)

    temp_password = secrets.token_urlsafe(18)
    output_bundle = out_dir / f"customer-local-{version}-{tenant_code}.tar.gz"

    with tempfile.TemporaryDirectory(prefix="gb_bundle_") as tmp:
        tmp_path = Path(tmp)
        with tarfile.open(source_bundle, "r:gz") as tar:
            tar.extractall(tmp_path)

        env_candidates = list(tmp_path.rglob("overlay/env/customer-local.env"))
        if not env_candidates:
            raise RuntimeError("customer_local_env_missing_in_bundle")

        env_path = env_candidates[0]
        env_path.write_text(_render_customer_env(env_path.read_text(), customer_profile, temp_password))

        with tarfile.open(output_bundle, "w:gz") as tar:
            for child in tmp_path.iterdir():
                tar.add(child, arcname=child.name)

    return output_bundle

def record_bundle_download(customer_profile: Dict[str, Any], bundle: Dict[str, Any]) -> Dict[str, Any]:
    customer_id = (customer_profile.get("customer_id") or "").strip()
    bundle_path = Path(bundle["bundle_path"])
    version = _extract_release_version_from_bundle_path(bundle_path)
    if not customer_id or not version:
        return {
            "customer_id": customer_id or None,
            "last_downloaded_release_version": version,
            "last_downloaded_at": None,
        }

    ts = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    row = update_customer_last_download(
        customer_id=customer_id,
        last_downloaded_release_version=version,
        last_downloaded_at=ts,
    )
    return row

def prepare_delivery_plan(customer_id: str) -> Dict[str, Any]:
    customer = get_customer_by_id(customer_id)

    assigned_release_version = (customer.get("assigned_release_version") or "").strip()
    if not assigned_release_version:
        raise RuntimeError("assigned_release_version_missing")

    tenant_code = (customer.get("tenant_code") or "").strip()
    company_name = (customer.get("company_name") or "").strip()

    return {
        "status": "planned",
        "customer_id": customer_id,
        "tenant_code": tenant_code,
        "company_name": company_name,
        "assigned_release_version": assigned_release_version,
        "message": "Bundle generation must run on host via tools/customer_ops/prepare_assigned_bundle.sh",
    }


def mark_delivery_sent(customer_id: str) -> Dict[str, Any]:
    delivery = get_delivery_row(customer_id)
    if not delivery:
        raise ValueError("delivery_row_missing")
    if not delivery.get("bundle_generated_at"):
        raise ValueError("bundle_not_generated_yet")

    ts = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    row = mark_bundle_sent(customer_id=customer_id, bundle_sent_at=ts)
    return {
        "status": "sent_marked",
        "customer_id": customer_id,
        "bundle_sent_at": row.get("bundle_sent_at", ts),
        "delivery": row,
    }


def resolve_bundle_download(customer_profile: Dict[str, Any]) -> Dict[str, Any]:
    payment_saved = customer_profile.get("payment_method_saved") is True
    slot_requested = bool(customer_profile.get("setup_slot_requested_at"))
    slot_confirmed = bool(
        customer_profile.get("setup_slot_confirmed_at")
        or customer_profile.get("setup_slot_scheduled_for")
    )

    if not payment_saved or not slot_requested or not slot_confirmed:
        raise RuntimeError("bundle_not_ready")

    # 1) Preferred source: latest release available on host, personalized per customer
    latest_bundle = _find_latest_release_bundle()
    if latest_bundle and latest_bundle.exists() and latest_bundle.is_file():
        personalized_bundle = _build_personalized_bundle(latest_bundle, customer_profile)
        return {
            "bundle_path": str(personalized_bundle),
            "filename": personalized_bundle.name,
            "source": "personalized_latest_release",
        }

    # 2) Fallback: per-customer prepared bundle path, if available
    delivery = customer_profile.get("delivery") or {}
    bundle_local_path = (delivery.get("bundle_local_path") or "").strip()
    if bundle_local_path:
        p = Path(bundle_local_path)
        if p.exists() and p.is_file():
            return {
                "bundle_path": str(p),
                "filename": p.name,
                "source": "customer_bundle",
            }
        raise RuntimeError(f"bundle_file_missing: {bundle_local_path}")

    raise RuntimeError("bundle_not_ready")
