-- GreenBrain source DB activation flow
-- Additive-only migration.
-- Purpose:
-- - keep gb_customer_companies.db_integration_status as workflow summary
-- - extend gb_customer_db_integrations with config, manager response,
--   formal validation, local technical checker result, and reports
-- - no data deletion
-- - no password stored in clear text

BEGIN;

ALTER TABLE public.gb_customer_db_integrations
  ADD COLUMN IF NOT EXISTS source_client_code text,
  ADD COLUMN IF NOT EXISTS db_view_name text,
  ADD COLUMN IF NOT EXISTS db_username text,
  ADD COLUMN IF NOT EXISTS db_password_encrypted text,
  ADD COLUMN IF NOT EXISTS db_password_set boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS db_encrypt boolean,
  ADD COLUMN IF NOT EXISTS db_trust_server_certificate boolean,
  ADD COLUMN IF NOT EXISTS manager_contact_email text,
  ADD COLUMN IF NOT EXISTS manager_response_raw_text text,
  ADD COLUMN IF NOT EXISTS manager_response_received_at timestamptz,
  ADD COLUMN IF NOT EXISTS formal_validation_status text NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS formal_validation_report text,
  ADD COLUMN IF NOT EXISTS formal_validation_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS formal_validation_at timestamptz,
  ADD COLUMN IF NOT EXISTS technical_test_status text NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS technical_test_report text,
  ADD COLUMN IF NOT EXISTS technical_test_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS technical_test_at timestamptz,
  ADD COLUMN IF NOT EXISTS checker_token_hash text,
  ADD COLUMN IF NOT EXISTS checker_token_created_at timestamptz,
  ADD COLUMN IF NOT EXISTS checker_token_expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_error_report text,
  ADD COLUMN IF NOT EXISTS last_error_at timestamptz;

COMMENT ON TABLE public.gb_customer_db_integrations IS
  'Per-customer source database integration config and validation state. Passwords must be encrypted, never stored in clear text.';

COMMENT ON COLUMN public.gb_customer_db_integrations.db_password_encrypted IS
  'Encrypted source DB password. Never expose to frontend or ops UI.';
COMMENT ON COLUMN public.gb_customer_db_integrations.manager_response_raw_text IS
  'Raw response pasted by customer from DB/software manager; may contain technical details and must be treated as sensitive.';
COMMENT ON COLUMN public.gb_customer_db_integrations.formal_validation_report IS
  'Human-readable formal validation report that customer/admin can send to DB manager.';
COMMENT ON COLUMN public.gb_customer_db_integrations.technical_test_report IS
  'Human-readable local technical test report generated by GreenBrain checker.';
COMMENT ON COLUMN public.gb_customer_db_integrations.checker_token_hash IS
  'Hash of temporary checker token used by local pre-install validation tool. Raw token is never stored.';

CREATE INDEX IF NOT EXISTS idx_gb_customer_db_integrations_formal_validation_status
  ON public.gb_customer_db_integrations(formal_validation_status);

CREATE INDEX IF NOT EXISTS idx_gb_customer_db_integrations_technical_test_status
  ON public.gb_customer_db_integrations(technical_test_status);

CREATE INDEX IF NOT EXISTS idx_gb_customer_db_integrations_checker_token_hash
  ON public.gb_customer_db_integrations(checker_token_hash);

CREATE INDEX IF NOT EXISTS idx_gb_customer_companies_db_integration_status
  ON public.gb_customer_companies(db_integration_status);

COMMIT;
